version: '3'
services:
  redis:
    image: redis
    logging:
      driver: awslogs
      options:
        awslogs-group: renupharm-redis
        awslogs-region: eu-west-1
        awslogs-stream-prefix: redis
  app_1:
    image: 348231524911.dkr.ecr.eu-west-1.amazonaws.com/renupharm
    environment:
      PORT: "3000"
      RAILS_ENV: "production"
      RACK_ENV: "production"
      NODE_ENV: "development"
      JOB_WORKER_URL: "redis://redis:6379/0"
    command: bash -c "rm -f /production/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - public-volume:/production/public/
    links:
      - redis
      - solr
    logging:
      driver: awslogs
      options:
        awslogs-group: renupharm-app-1
        awslogs-region: eu-west-1
        awslogs-stream-prefix: rails
  app_2:
    image: 348231524911.dkr.ecr.eu-west-1.amazonaws.com/renupharm
    environment:
      PORT: "3000"
      RAILS_ENV: "production"
      RACK_ENV: "production"
      NODE_ENV: "development"
      JOB_WORKER_URL: "redis://redis:6379/0"
    command: bash -c "rm -f /production/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - public-volume:/production/public/
    links:
      - redis
      - solr
    logging:
      driver: awslogs
      options:
        awslogs-group: renupharm-app-2
        awslogs-region: eu-west-1
        awslogs-stream-prefix: rails
  sidekiq:
    image: 348231524911.dkr.ecr.eu-west-1.amazonaws.com/renupharm
    command: bundle exec sidekiq -q default -q mailers
    links:
      - redis
    environment:
      PORT: "3000"
      RAILS_ENV: "production"
      RACK_ENV: "production"
      NODE_ENV: "development"
      JOB_WORKER_URL: "redis://redis:6379/0"
    logging:
      driver: awslogs
      options:
        awslogs-group: renupharm-sidekiq
        awslogs-region: eu-west-1
        awslogs-stream-prefix: sidekiq
  web:
    image: 348231524911.dkr.ecr.eu-west-1.amazonaws.com/renupharm-nginx
    volumes:
      - public-volume:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    links:
      - app_1
      - app_2
    logging:
      driver: awslogs
      options:
        awslogs-group: renupharm-nginx
        awslogs-region: eu-west-1
        awslogs-stream-prefix: nginx
  solr:
    image: 348231524911.dkr.ecr.eu-west-1.amazonaws.com/renupharm-solr
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - default
      - /opt/solr/server/solr/configsets/sunspot
    logging:
      driver: awslogs
      options:
        awslogs-group: renupharm-solr
        awslogs-region: eu-west-1
        awslogs-stream-prefix: solr
volumes:
  public-volume:
  solr_indices:
