version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
     - /usr/local/renupharm/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "s2cr2t"
  redis:
    image: redis
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "rm -f /production/tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/production
      - public-volume:/production/public/
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      RAILS_ENV: "development"
      NODE_ENV: "development"
      RAILS_ENV: "development"
      JOB_WORKER_URL: "redis://redis:6379/0"
    links:
      - db:mysql_cont
    depends_on:
      - db
  web:
    build:
      context: ./docker/web
      args:
        nginx_env: $NGINX_ENV
    volumes:
      - public-volume:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
  webpacker:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "WEBPACKER_DEV_SERVER_HOST=0.0.0.0 ./bin/webpack-dev-server"
    volumes:
      - .:/production
    ports:
      - "3035:3035"
  sidekiq:
    image: renupharm_app:latest
    command: bundle exec sidekiq -q default -q mailers
    volumes:
      - .:/production
    depends_on:
      - db
      - redis
    environment:
      PORT: "3000"
      RAILS_ENV: "development"
      NODE_ENV: "development"
      RAILS_ENV: "development"
      JOB_WORKER_URL: "redis://redis:6379/0"
volumes:
  public-volume:
