version: '3'
services:
  app_1:
    image: 348231524911.dkr.ecr.eu-west-1.amazonaws.com/renupharm
    environment:
      PORT: "3000"
      RAILS_ENV: "production"
      RACK_ENV: "production"
      NODE_ENV: "development"
    command: bash -c "rm -f /production/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - public-volume:/production/public/

  app_2:
    image: 348231524911.dkr.ecr.eu-west-1.amazonaws.com/renupharm
    environment:
      PORT: "3000"
      RAILS_ENV: "production"
      RACK_ENV: "production"
      NODE_ENV: "development"
    command: bash -c "rm -f /production/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - public-volume:/production/public/
  web:
    image: 348231524911.dkr.ecr.eu-west-1.amazonaws.com/renupharm-nginx
    volumes:
      - public-volume:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    links:
      - app_1
      - app_2
volumes:
  public-volume:
