version: '3'
services:
  redis:
    image: redis
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  app_1:
    image: 348231524911.dkr.ecr.eu-west-1.amazonaws.com/renupharm
    network_mode: bridge
    environment:
      PORT: "3000"
      RAILS_ENV: "production"
      RACK_ENV: "production"
      NODE_ENV: "development"
      JOB_WORKER_URL: "redis://redis:6379/0"
    command: bash -c "rm -f /production/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - public-volume:/production/public/
    links:
      - redis
      - solr
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  app_2:
    image: 348231524911.dkr.ecr.eu-west-1.amazonaws.com/renupharm
    network_mode: bridge
    environment:
      PORT: "3000"
      RAILS_ENV: "production"
      RACK_ENV: "production"
      NODE_ENV: "development"
      JOB_WORKER_URL: "redis://redis:6379/0"
    command: bash -c "rm -f /production/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - public-volume:/production/public/
    links:
      - redis
      - solr
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  sidekiq:
    image: 348231524911.dkr.ecr.eu-west-1.amazonaws.com/renupharm
    network_mode: bridge
    command: bundle exec sidekiq -q default -q mailers
    links:
      - redis
    environment:
      PORT: "3000"
      RAILS_ENV: "production"
      RACK_ENV: "production"
      NODE_ENV: "development"
      JOB_WORKER_URL: "redis://redis:6379/0"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  solr:
    image: 348231524911.dkr.ecr.eu-west-1.amazonaws.com/renupharm-solr
    network_mode: bridge
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - default
      - /opt/solr/server/solr/configsets/sunspot
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
volumes:
  public-volume:
  solr_indices:
