version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "s2cr2t"
  app_1:
    build:
      context: $PWD
      dockerfile: ./docker/app/Dockerfile
    #command: bash -c "rm -f /production/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "sleep 5000"
    volumes:
      - .:/production
      - public-volume:/production/public/
    environment:
      PORT: "3000"
      MYSQL_HOST: "db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "s2cr2t"
      MYSQL_DATABASE: "renupharm"
      NODE_ENV: "development"
    links:
      - db:mysql_cont
    depends_on:
      - db
  app_2:
    build:
      context: $PWD
      dockerfile: ./docker/app/Dockerfile
    #command: bash -c "rm -f /production/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "sleep 5000"
    volumes:
      - .:/production
      - public-volume:/production/public/
    environment:
      PORT: "3000"
      MYSQL_HOST: "db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "s2cr2t"
      MYSQL_DATABASE: "renupharm"
      NODE_ENV: "development"
    depends_on:
      - db
  web:
    build:
      context: ./web
      args:
        nginx_env: "development"
    volumes:
      - public-volume:/var/local/web
    ports:
      - "80:80"
    depends_on:
      - app_1
      - app_2
volumes:
  public-volume:
