production:
  solr:
    hostname: solr
    port: 8983
    log_level: WARNING
    solr_home: solr
    path: /solr/default
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: solr
    port: 8983
    log_level: INFO
    solr_home: solr
    path: /solr/default

test:
  solr:
    hostname: solr
    port: 8983
    log_level: WARNING
    solr_home: solr
    path: /solr/default
